### ISSUE TITLE
Failed resolution of: Lcz/msebera/android/httpclient/client/utils/URIBuilder;

### ISSUE THREAD

**Issue by jigneshhadiya2** [microsoftgraph/msgraph-sample-android#59]
When i use latest identity dependancy i got this error "java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: Failed resolution of: Lcz/msebera/android/httpclient/client/utils/URIBuilder;"

**Comment by jasonjoh** [comment]
I can't reproduce this. I just updated the sample in https://github.com/microsoftgraph/msgraph-training-android/pull/60 to use the latest MSAL library.

https://github.com/microsoftgraph/msgraph-training-android/blob/3bc832e7933325ca9d2ebdb00fe84b37c23598b4/src/app/build.gradle#L40
